name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        id: run_tests
        run: |
          pytest

      - name: Build Docker image
        if: success()
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/myapp:latest .

      - name: Log in to GitHub Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: success()
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/myapp:latest

  notify-failure:
    if: failure()
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Send failure notification via SendGrid
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [{
                "to": [{"email": "ctdobson@dons.usfca.edu"}]
              }],
              "from": {"email": "colbytdobson@gmail.com"},
              "template_id": "'"d-d2e76e4034834b0f8a00f202f2f0649a"'"
            }'
